# Generated by Django 3.1.4 on 2021-06-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210601_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/images/default_image.jpg', upload_to='profile_pic'),
        ),
    ]
