# Generated by Django 3.1.4 on 2021-06-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210601_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/static/images/default_profile_image.jpg', upload_to='profile_pic'),
        ),
    ]
