# Generated by Django 3.2 on 2021-06-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210602_0620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTags',
            new_name='PostTag',
        ),
    ]
